### ISSUE TITLE
KeyError: 'No such transport: ' trying to run Celery

### ISSUE THREAD

**Issue by bootrino** [sirodoht/opencult.com#43]
Hi there

I'm trying to get this project running.

I got everything else working except Celery.  I got this error:  Any suggestions? thanks!

```
(venv3.6) ubuntu@ip-10-0-7-68:/opt/foo$ celery -A opencult worker -P gevent -l debug
Traceback (most recent call last):
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/kombu/transport/__init__.py", line 55, in resolve_transport
    transport = TRANSPORT_ALIASES[transport]
KeyError: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/foo/venv3.6/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
    _main()
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
    cmd.execute_from_commandline(argv)
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/celery/bin/base.py", line 281, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/celery/bin/celery.py", line 480, in handle_argv
    return self.execute(command, argv)
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/celery/bin/celery.py", line 412, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/celery/bin/worker.py", line 221, in run_from_argv
    return self(*args, **options)
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/celery/bin/base.py", line 244, in __call__
    ret = self.run(*args, **kwargs)
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/celery/bin/worker.py", line 255, in run
    **kwargs)
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/celery/worker/worker.py", line 99, in __init__
    self.setup_instance(**self.prepare_args(**kwargs))
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/celery/worker/worker.py", line 120, in setup_instance
    self._conninfo = self.app.connection_for_read()
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/celery/app/base.py", line 752, in connection_for_read
    return self._connection(url or self.conf.broker_read_url, **kwargs)
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/celery/app/base.py", line 828, in _connection
    'broker_connection_timeout', connect_timeout
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/kombu/connection.py", line 179, in __init__
    if not get_transport_cls(transport).can_parse_url:
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/kombu/transport/__init__.py", line 83, in get_transport_cls
    _transport_cache[transport] = resolve_transport(transport)
  File "/opt/foo/venv3.6/lib/python3.6/site-packages/kombu/transport/__init__.py", line 64, in resolve_transport
    raise KeyError('No such transport: {0}'.format(transport))
KeyError: 'No such transport: '
(venv3.6) ubuntu@ip-10-0-7-68:/opt/foo$
```

**Comment by sirodoht** [comment]
Hey,

Not sure about that, I have not faced it myself. 

Can you verify you have Redis installed and the `.env` file populated?

**Comment by bootrino** [comment]
Looks like I do have it in my .env file.

I found I can make it work, but only if I manually do this:

export CELERY_BROKER_URL=redis://@localhost


```
(venv3.6) ubuntu@ip-10-0-7-68:/opt/foo$ cat .env
DATABASE_URL="postgres://foouser:foopassword$@localhost:5432/foo"
REDIS_URL="redis://@localhost:6379"  # used for celery worker, see below
SECRET_KEY="thisisthesecretkey"
EMAIL_HOST_USER="fookey"  # optional, only for email functionality
EMAIL_HOST_PASSWORD="foopassword"  # optional, only for email functionality

```

**Comment by sirodoht** [comment]
It might seem there is an issue with dotenv loading in [this line](https://github.com/sirodoht/opencult.com/blob/2557b71bde0625cbcd7d154e5f0f6c7609af1361/opencult/celery_tasks.py#L8). I am not experiencing it on macOS, it might be Ubuntu-specific. Feel free to verify it by commenting out that line and checking if the issue persists.

**Comment by hassek** [comment]
@bootrino This was happening to me as well, I removed the `"` out of the environment variables and it started working properly.

**Comment by sirodoht** [comment]
@hassek Interesting, what's your operating system and shell?

**Comment by hassek** [comment]
zsh and MacOs High Sierra

**Comment by hassek** [comment]
@sirodoht zsh and MacOs, using iTerm2 and tmux (if that helps at all hehe)

**Comment by michael-burt** [comment]
Hit the same problem on osx high sierra

**Comment by BrandoZhang** [comment]
I've tried @hassek's solution but it does not work. I manually tap 
`"export CELERY_BROKER_URL_DEV=pyamqp://guest@localhost//"`
like @bootrino and solved it.

**Comment by iammeizu** [comment]
I met this problem when using flower, and I find out the reason is the boot cmd was write from "--broker" to "-broker".

**Comment by sirodoht** [comment]
Just to note, in the latest version celery has been replaced with django-background-tasks.

**Comment by dphans** [comment]
Did you deploy on docker? Recheck the environment value, may be url inside double/single quote. Remove quotes then restart container.

**Comment by honghuynhit** [comment]
> @bootrino This was happening to me as well, I removed the `"` out of the environment variables and it started working properly.

IT WORK!
